### ISSUE TITLE
Error after updating - map not allowed here

### ISSUE THREAD

**Issue by daedric7** [NginxProxyManager/nginx-proxy-manager#3474]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

After updating NPM ( docker compose pull && docker compose up -d) everything was OK until i edited a host.

After that the host started failing. After some debug i found a entry in /var/log/nginx/error.log stating 

"map not allowed here"

I managed to find the map entry in the middle of the conf and it's this:

```
  map $scheme $hsts_header {
    https   "max-age=63072000; preload";
}
```

This is suffixed on each of my custom locations for that host.

I edited the `_hsts_map.conf` to comment them and the error was solved, but this won't survive a docker restart.

**Nginx Proxy Manager Version**

v2.11.0 © 2024 [jc21.com](https://jc21.com/?utm_source=nginx-proxy-manager).

**To Reproduce**
1. Update to latest
2. Edit any host
3. Save

**Comment by Kingi-s** [comment]
I just did a fresh install of npm and the custom locations also dont work for me.

**Comment by exenza** [comment]
Have same issue, the error is actually visible as well in the UI

![issue](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/6783866/8d3f795e-f25b-430a-9912-c42c4aee0ec4)

**Comment by daedric7** [comment]
> Have same issue, the error is actually visible as well in the UI
> 
> ![issue](https://private-user-images.githubusercontent.com/6783866/298311948-8d3f795e-f25b-430a-9912-c42c4aee0ec4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTM0MDEsIm5iZiI6MTcwNTc5MzEwMSwicGF0aCI6Ii82NzgzODY2LzI5ODMxMTk0OC04ZDNmNzk1ZS1mMjViLTQzMGEtOTkxMi1jNDJjNGFlZTBlYzQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMjMyNTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDExOWRmMmNkMzI3NzIyMWNjODdlMTQ3M2JlZWFhZmNiZjBiOWRmZGRlYzY5N2QyOTg2OTQwODI2MzAwZTQ4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O_YkYLss4my7EBfSL4a-BzOqQah2Lwcn64dumeLzCII)

Question:

How did you get that error popup ? I had to go miles to figure out what the error was :)

**Comment by Kingi-s** [comment]
> > Have same issue, the error is actually visible as well in the UI
> > ![issue](https://private-user-images.githubusercontent.com/6783866/298311948-8d3f795e-f25b-430a-9912-c42c4aee0ec4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTM0MDEsIm5iZiI6MTcwNTc5MzEwMSwicGF0aCI6Ii82NzgzODY2LzI5ODMxMTk0OC04ZDNmNzk1ZS1mMjViLTQzMGEtOTkxMi1jNDJjNGFlZTBlYzQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMjMyNTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDExOWRmMmNkMzI3NzIyMWNjODdlMTQ3M2JlZWFhZmNiZjBiOWRmZGRlYzY5N2QyOTg2OTQwODI2MzAwZTQ4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O_YkYLss4my7EBfSL4a-BzOqQah2Lwcn64dumeLzCII)
> 
> Question:
> 
> How did you get that error popup ? I had to go miles to figure out what the error was :)

Hover your mouse over the red ball before the Offline text. i also found it by accident.

**Comment by daedric7** [comment]
Workaround:

create empty file named `_hsts_map.conf` on the same dir as `docker-compose.yaml`. 

Add this line to the volumes of `docker-compose.yaml` :

`- ./_hsts_map.conf:/app/templates/_hsts_map.conf`

**Comment by 573dave** [comment]
Same issue here. And since I'm using unraid I can't figure out the workaround.

**Comment by ghTravis** [comment]
Also experiencing the same issue here. Just tried to add a new proxy host with custom locations. Appearing Offline.

**Comment by rasturic** [comment]
jc21/nginx-proxy-manager:github-pr-3478 fixes it for me.

**Comment by aphex3k** [comment]
When running as part of TrueNAS Apps (in k8s), the included configuration UI doesn't allow for adding a custom volume so the suggested workaround can not be applied.

> `- ./_hsts_map.conf:/app/templates/_hsts_map.conf`

Changing the tag from `latest` is also not possible, so one can not roll-back to a previous version or test the custom resource location.

This breaks custom locations on TrueNAS without fix for now.

**Comment by liukonen** [comment]
Tried with the following
- ./_hsts_map.conf:/app/templates/_hsts_map.conf
Domain works again, but custom locations still not working

**Comment by alarifgit** [comment]
> jc21/nginx-proxy-manager:github-pr-3478

This worked for me but I had to delete the custom location and re-create it before the site showed as online again.

**Comment by AkshayRao27** [comment]
Here's what worked for me: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3512#issuecomment-1940868886

**Comment by AxxiD** [comment]
Still having the same problem.
The workaround with an empty `_hsts-map.conf` file works but is not ideal.

**Comment by asher-lab** [comment]
This is also what I'm currently experiencing as of February 23, 2024

**Comment by malavolti** [comment]
Same problem here and I have tried all workarounds.

**Comment by Kevinsky86** [comment]
> Workaround:
> 
> create empty file named `_hsts_map.conf` on the same dir as `docker-compose.yaml`.
> 
> Add this line to the volumes of `docker-compose.yaml` :
> 
> `- ./_hsts_map.conf:/app/templates/_hsts_map.conf`

This workaround works for me as well. 
But you do have to re-add the custom location, which might be a PITA if you have a lot of locations/hosts...
This needs a real fix quite promptly.

**Comment by malavolti** [comment]
I don't know if someone of you are using "custom locations" to provide different web services from different docker containers, but I think this is very useful thing.

If someone has already done this, can help me to understand how to do it, please?

```
Docker Container | PORT | Location
site             | 8080 | https://my-website.example.org/
phpmyadmin       | 8081 | https://my-website.example.org/phpmyadmin
mailserver       | 8082 | https://my-website.example.org/mailer
```

**Comment by daedric7** [comment]
> I don't know if someone of you are using "custom locations" to provide different web services from different docker containers, but I think this is very useful thing.
> 
> If someone has already done this, can help me to understand how to do it, please?
> 
> ```
> Docker Container | PORT | Location
> site             | 8080 | https://my-website.example.org/
> phpmyadmin       | 8081 | https://my-website.example.org/phpmyadmin
> mailserver       | 8082 | https://my-website.example.org/mailer
> ```

Avoid this.

Not all services will be happy to be served under a subdir ( https://example.oeg/subdir/ ).

You should use subdomains when possible, so www.example.org , phpmyadmin.example.org, mail.example.org.

You create a individual entry in NPM for each service. Also, this is offtopic for this issue.

**Comment by malavolti** [comment]
Thank you so much @daedric7 !

I'll follow your suggestion! 😊

**Comment by TheUntouchable** [comment]
Still this problem is happening with a fresh installation..

**Comment by dudefoxlive** [comment]
Well this is annoying. At least there is a workaround for now.

**Comment by nomad-geek** [comment]
> Workaround:
> 
> create empty file named `_hsts_map.conf` on the same dir as `docker-compose.yaml`.
> 
> Add this line to the volumes of `docker-compose.yaml` :
> 
> `- ./_hsts_map.conf:/app/templates/_hsts_map.conf`

Solved the problem for me. Thanks.

**Comment by kachunkachunk** [comment]
Weird one. The workaround of mapping a blank `_hsts_map.conf` file didn't work for me, nor did downgrading to [2.11.1](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.11.1).

Evidently, some of my confs in `/data/nginx/proxy_host/` were already tainted with extraneous `map` directives, so nginx was failing to start properly.

I'm still downgraded and have not tried going back to 2.11.1, but:

I resolved this by checking the container logs with `docker logs <nginx-proxy-manager container name>` and seeing what line called out in the error. For instance:

```
❯ Starting nginx ...
nginx: [emerg] "map" directive is not allowed here in /data/nginx/proxy_host/2.conf:383
[4/21/2024] [9:57:02 AM] [SSL      ] › ✖  error     Error: Command failed: /usr/sbin/nginx -t -g "error_log off;"
nginx: [emerg] "map" directive is not allowed here in /data/nginx/proxy_host/2.conf:383
nginx: configuration file /etc/nginx/nginx.conf test failed

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5
```

In this case, it's for a particularly long proxy host I set up (lots of locations), at line 383.

I took to editing the file (`./data/nginx/proxy_host/2.conf`) and commenting out the offending lines:
```
#  map $scheme $hsts_header {
#    https   "max-age=63072000; preload";
#}
```

I then saved the file and restarted the container, observing the logs for potential errors. Because Nginx exits on the first fatal error in the configs, you won't see all of them at once, and have to repeat this process a few times. But after 7-8 or so of these (and confirming I'm not seeing the same approximate line numbers re-appear), I eventually cleared the bad entries out.

It took a few minutes and I did not have to recreate my locations.

**Comment by JBlond** [comment]
@kachunkachunk The config is saved in the database. Once you override that _hsts_map.conf the variable that is used in the vhosts is no longer set.

**Comment by manelrodero** [comment]
Upgrading to 2.11.2 solved the problem for me. No more "offline" when using "custom locations":

https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.11.2

**Comment by brentonmallen1** [comment]
If anyone is attempting to make this work with Authentik, this workaround seems to be working for me:

```
# Upgrade WebSocket if requested, otherwise use keepalive
    #map $http_upgrade $connection_upgrade_keepalive {       
    #    default upgrade;                                                                  
    #    ''      '';                                                                 [COMMENT OUT THIS MAP SECTION]
    #}                                                                 
# Increase buffer size for large headers
# This is needed only if you get 'upstream sent too big header while reading response
# header from upstream' error when trying to access an application protected by goauthentik
proxy_buffers 8 16k;
proxy_buffer_size 32k;

# Make sure not to redirect traffic to a port 4443
port_in_redirect off;

location / {
    # Put your proxy_pass to your application here
    proxy_pass          $forward_scheme://$server:$port;
    # Set any other headers your application might need
    # proxy_set_header Host $host;
    # proxy_set_header ...
    # Support for websocket
    proxy_set_header Upgrade upgrade;                     [SET THESE TWO VARIABLES TO THE DEFAUL VALUE OF 'upgrade']
    proxy_set_header Connection upgrade;                 
```

Then ensure that the proxy host setting in nginx proxy manager is set to `https` so that the upgrade happens.

This was after updating to the latest container version (2.11.2)

**Comment by skyzuma** [comment]
the mentionen in this link is for "OAuth2/OpenID Provider" only, this entrys dont need a "Custom Nginx Configuration" ... an app with websocket like audiobookshelf and authentik proxy provider will not work cause of this "map not allowed here" in the "Custom Nginx Configuration" ... and its not fixed in 2.11.2 ... i use unraid with latest nginx proxy manager version ...

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/1676196/431cad29-dbd1-4702-8dd7-5cf300a6f27c)

**Comment by icvdok** [comment]
Just updated to ver 2.11.2 but the problem persist with Authentik proxy provider. There are news about the fix?

**Comment by brentonmallen1** [comment]
fwiw, I wound up just switching to the `jlesage/nginx-proxy-manager` container in unraid

**Comment by pwall2222** [comment]
This bug was fixed back in 10ece3548d42aa5dba424816f065827fdaf3f990 and it was released into the public with [v2.11.2](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.11.2).
This issue (and all duplicate) should be closed.

**Comment by tobymills** [comment]
I had this issue with Nginx & Authetix because authentik template for Nginx is trying to map a header in the wrong place.
I did the following to fix this for those that also get this issue.


Create http_top.conf in data/nginx/custom (create custom folder in data/nginx/ if it doesn't exist)

Add following code to the file:
```
map $http_upgrade $connection_upgrade {
		default upgrade;
		  ''      close;
}
```

restart nginx

remove the lines from top of authentik Nginx template that have this code
```
# Upgrade WebSocket if requested, otherwise use keepalive
map $http_upgrade $connection_upgrade_keepalive {
    default upgrade;
    ''      '';
}
```

Update the line: 
`proxy_set_header Connection $connection_upgrade_keepalive;`

To 
`proxy_set_header Connection $connection_upgrade;
`
_remember to set proxy_pass to local IP address of Authentix server, not Nginx DNS as this caused me issues...._

**Comment by ramphex** [comment]
I don't understand how this is closed as completed if I'm still getting this issue, even with 2.11.3 and the only way to fix it is with the tomfoolery that tobymills posted.

**Comment by ramphex** [comment]
Still having this issue. Is it Authentik or is it NPM to blame?

**Comment by motoridersd** [comment]
> proxy_set_header Connection $connection_upgrade;

I followed your instructions and my error went from "map not allowed here" to "unknown connection_upgrade" variable. The original connection_upgrade_keepalive doesn't work either.

I'm on 2.11.3 so not sure if things have changed. I was still having the map error with Authentik before making your suggested change.

**Comment by heavymp** [comment]
> I had this issue with Nginx & Authetix because authentik template for Nginx is trying to map a header in the wrong place. I did the following to fix this for those that also get this issue.
> 
> Create http_top.conf in data/nginx/custom (create custom folder in data/nginx/ if it doesn't exist)
> 
> Add following code to the file:
> 
> ```
> map $http_upgrade $connection_upgrade {
> 		default upgrade;
> 		  ''      close;
> }
> ```
> 
> restart nginx
> 
> remove the lines from top of authentik Nginx template that have this code
> 
> ```
> # Upgrade WebSocket if requested, otherwise use keepalive
> map $http_upgrade $connection_upgrade_keepalive {
>     default upgrade;
>     ''      '';
> }
> ```
> 
> Update the line: `proxy_set_header Connection $connection_upgrade_keepalive;`
> 
> To `proxy_set_header Connection $connection_upgrade; ` _remember to set proxy_pass to local IP address of Authentix server, not Nginx DNS as this caused me issues...._

This has worked for me too. Thanks. Hope fix will be implemented in next NPM

**Comment by kolby-macdonald** [comment]
SOLUTION (Hacky):

Make sure to mount the following volumes:
```
      - './nginx-data:/data'
      - './nginx-certs:/etc/letsencrypt/'
      - './_hsts_map.conf:/app/templates/_hsts_map.conf'
```

After adding the reverse proxy, open it's respective config file `sudo nano nginx-volumes/nginx-data/nginx/proxy_host/<config-number>.conf`. You can get the <config number> from clicking on the vertical ellipses (or three dot menu) where you would edit the entity.

3.  In that file, you will see something similar to the following:
```
server {
  set $forward_scheme http;
  set $server         "<ip>";
  set $port           <port>;
```

After the port you can add your desired path as shown below:
```
server {
  set $forward_scheme http;
  set $server         "<ip>";
  set $port           <port/your-desired-path/>;
```

:) Hope this helps someone.

**Comment by AxxiD** [comment]
Will this get any update or fix? It is still an issue

**Comment by AkshayRao27** [comment]
I switched to NPMplus. It fixes a bunch of issues.

**Comment by JBlond** [comment]
@AkshayRao27 Do you mind to share the  URL?

**Comment by AkshayRao27** [comment]
> [@AkshayRao27](https://github.com/AkshayRao27) Do you mind to share the URL?

Here you go https://github.com/ZoeyVid/NPMplus
