### ISSUE TITLE
No custom location possible!

### ISSUE THREAD

**Issue by XHyperDEVX** [NginxProxyManager/nginx-proxy-manager#3508]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

I cannot define a custom subpath. Today at noon everything still worked, but not anymore. I have reinstalled NPM, same error. What is the reason?
When I put it in like this, the entry goes offline. If I take it out, it works again. It seems to be a syntax problem. I can't explain it any other way
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/68189420/c408e698-4929-4032-a426-f87468d2d3a6)
the npm container is in the same network as the apache2 container. [-> before it worked the same way. it also does not work if i replace "apache2" with the ip of the container]

**Nginx Proxy Manager Version**
v2.11.1

**To Reproduce**
1. Add"Custom Location" Entry

**Expected behavior**
The entry does not go offline

**Screenshots**
see above

**Operating System**
Debian with Docker

**Additional context**
no

**Comment by irrwitzer42** [comment]
I can second this observation.
What worked in 2.10.4 just fine, does not with 2.11.1:

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/25076496/554fad6b-01b7-455b-adf7-eb759152d806)

Unfortunately the config file gets deleted / not created, so I could not check it any deeper.

**Comment by XHyperDEVX** [comment]
i have the same error as you in the picture. we definitely have the same problem.

**Comment by irrwitzer42** [comment]
This seems to be a duplicate of https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3484 and https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3474
I rolled back to 2.10.4 on all my NPMs for now. Waiting for the next release.

**Comment by RajawatBanna** [comment]
I am also facing this issue and done hello lot of googling, changing rule until i found this page.

**Comment by Wek-mad** [comment]
I also having the same error, some how the add_header cannot write to the conf file and it made the proxy stop.
hope this bug fix soon

**Comment by jackfalveyiv** [comment]
Running NPM on Unraid, ran into this problem on a fresh new install of the docker.  Hosts were working fine before that, but the same configuration under the custom location that previously worked immediately makes the proxy host go offline.

**Comment by MiguelTVMS** [comment]
The same problem is happening to me.

**Comment by AkshayRao27** [comment]
I had a similar issue where teslamate-local.mydomain.com was working but teslamate-local.mydomain.com/grafana was showing a blank page that said "Not Found". https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3512#issuecomment-1940868886 is how I fixed it.

**Comment by masterwishx** [comment]
Same issue with lasted version using portainer in Oracle Cloud

**Comment by EDIflyer** [comment]
custom locations still don't seem seem to work for me on v.2.12.1

**Comment by gthvidsten** [comment]
Same for v2.12.3 :(

**Comment by gthvidsten** [comment]
Okay, I actually got it to work with v2.12.3.
It's really really sensitive about slashes.

Setting up a custom location with `/mypath/` pointing to hostname `myhost/` works. Note the trailing slashes everywhere.

So:
Having a trailing slash in location but not hostname: Doesn't work.
Having no trailing slashes in neither location nor hostname: Doesn't work.
Having trailing slashes for both location and hostname: Works!

Might be something that should be automatically added.

[This link](https://stackoverflow.com/a/58912470/4353606) tipped me off:
I edited directly in the `datamount/nginx/proxy_host/<hostnumber>.conf` and experimented with the `location` directive. I then disabled/enabled another host to reload the configs, and it started working.
I could then recreating the behaviour in the UI.

**Comment by adrianfurgol** [comment]
this still does not work. For me, as soon as I add a custom location, the entire `.conf` file vanishes:

```
# currently everything is working
adrian@vps:/opt/stacks/nginx-proxy-manager/data/nginx/proxy_host$ ls
15.conf  1.conf  3.conf  4.conf  6.conf  7.conf

# now I add a custom location
adrian@vps:/opt/stacks/nginx-proxy-manager/data/nginx/proxy_host$ ls
1.conf  3.conf  4.conf  6.conf  7.conf      # boom, its gone
```

All of this is happening without any error in the logs, and no feedback to the frontend, which is extemely frustrating.

Even trailing/leading `/` did not fix it.

**Comment by kencinder** [comment]
Still isn't working, I have tried several different custom configurations to make this work and nothing does, none of the above suggestions or added / anywhere.

**Comment by AkshayRao27** [comment]
> Still isn't working, I have tried several different custom configurations to make this work and nothing does, none of the above suggestions or added / anywhere.

I gave up and switched to using NPMplus.

**Comment by adrianfurgol** [comment]
I figured out it out (I think). I'm only guessing, but it seems like it checks if the destination is reachable upon saving. If it is not, this bug happens and the whole .conf file disappears. So you probably have a faulty destination. But feel free to correct me.

**Comment by kencinder** [comment]
> I figured out it out (I think). I'm only guessing, but it seems like it checks if the destination is reachable upon saving. If it is not, this bug happens and the whole .conf file disappears. So you probably have a faulty destination. But feel free to correct me.

The proxy host I have configred has worked fine for months, I just have to add the path in my browser address bar and I would rather not.
So the destination is fine and works otherwise.
