### ISSUE TITLE
satisfy_any toggle not working

### ISSUE THREAD

**Issue by mikeymasonic** [NginxProxyManager/nginx-proxy-manager#4088]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Whenever I set "Satisfy Any" in an access list details section, it doesn't work. For instance if I have an HTTP Auth setup and an IP route, if I access that particular proxy on a whitelisted IP, I get prompted for HTTP authentication.  If I go to the proxy with a non whitelisted IP, I get 403 Forbidden and no HTTP Auth prompt. The check box does save the previous saved state however.

I've taken a look at the config files and I notice this near the end:

```
# Access checks must...
    
    satisfy all;
```

If I manually change this to `satisfy any;`, everything works as expected.

Another unrelated issue, I notice in the GUI I'm on version v2.12.1, but in my docker instance I see:  `NPM_BUILD_VERSION | 2.11.3`

If I login to my docker container I see: `Version 2.11.3 (35d7a3a) 2024-07-01 11:42:06 UTC` 
I've pulled the latest image several times.

**Nginx Proxy Manager Version**

v2.12.1

**To Reproduce**
1. Access Lists
2. Edit an existing list
3. Add a valid whitelist ip
4. Add an HTTP login/password
5. Ensure `Satisfy Any` is checked
6. Save
7. Try to access proxy with your whitelisted IP, you'll still see an HTTP login
8. Try to access proxy with non whitelisted IP, you'll get 403 - Forbidden
9. If you manually change your proxy config file from `satisfy all;` to `satisfy any;`, everything works as expected

**Expected behavior**

- No HTTP Auth prompt if using a whitelisted IP and access
- HTTP Auth prompt if using a non whitelisted IP instead of a 403

**Screenshots**

**Operating System**

Using a docker instance on Ubuntu

**Additional context**

**Comment by binary-person** [comment]
rolling back to 2.11.3 fixes it, but updating it to 2.12.0 or 2.12.1 breaks it

**Comment by binary-person** [comment]
it seems that rolling back to "2.11.3" works, but updating it to "2.12.0" and "2.12.1" breaks it

**Comment by Gabri3lZ** [comment]
It looks like the commit 4572b205c912db498706e9a3e8f1891c94129c88 changed some model types from integer to boolean (one of them is the satisfy_any field). But the evaluation still checks for "satisfy_any == 1".

I don't know if this is the only case the evaluation does not match the model type anymore though.

**Comment by Gabri3lZ** [comment]
Should be fixed by dad8d0c from @chrismaffey

**Comment by bill340** [comment]
satisfy any is always overwritten to satisfy all in the .conf file after restarting the Nginx container.
So the toggle in the GUI and also what I write in the .conf file is not used, but overwritten again...

**Comment by allenwakeup** [comment]
/backend/templates/_access.conf (line 20)
change from
{% if access_list.satisfy_any == 1 %}
to
{% if access_list.satisfy_any == 1 or access_list.satisfy_any == true %}

docker v2.12.1

**Comment by ghisch** [comment]
You can temporarily use `nginxproxymanager/nginx-proxy-manager-dev:pr-4107` as it was fixed 2W ago in https://github.com/NginxProxyManager/nginx-proxy-manager/pull/4107.

Should be fixed in next release I guess.

**Comment by deluxestyle** [comment]
is there any update on this? 
already looking for alternatives as I don't get the developer build running

**Comment by mikeymasonic** [comment]
@deluxestyle, I tried with the latest developer build as it shows that the PR has been merged, I use this with docker: `nginxproxymanager/nginx-proxy-manager-dev:latest` to pull the image.  That said, it still doesn't work for me 🫠 .

Here is a script I wrote you can run on whatever machine hosts your docker instance, it changes anything that says `satisfy all` to `satisfy any` in the `proxy_host/*.conf` section.  I just run this whenever I have to make a change, it's annoying but it works.

```
sudo docker exec nginxpm bash -c 'for file in /data/nginx/proxy_host/*.conf; do sed -i "s/satisfy all;/satisfy any;/g" "$file"; done'
```
Hope this is helpful while we wait!

**Comment by Percy2Live** [comment]
Found this after searching for 2 hours why my configs aren't working anymore. switching to a dev branch isn't an option for me, so I guess I need to roll back to 2.11.3. 

Seems like a simple bug and the solution is already present. When is this going to be fixed in the main branch?

**Comment by FaySmash** [comment]
I can confirm that it is fixed in 2.12.2

**Comment by vorwd** [comment]
confirmed 2.12.12 fixes.
