### ISSUE TITLE
Cannot Log into Admin After Upgrade to 2.12.4

### ISSUE THREAD

**Issue by paelan8a** [NginxProxyManager/nginx-proxy-manager#4606]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes ([#1769](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1769))

**Describe the bug**
After upgrading from 2.12.3 to 2.12.4, I can no longer log into the admin panel. The login page is displayed, but authentication does not work. The Docker logs show the following and do not proceed any further:
```
nginx  | ❯ Starting backend ...
nginx  | [7/1/2025] [11:29:07 AM] [Global   ] › ℹ  info      Using Sqlite: /data/database.sqlite
nginx  | [7/1/2025] [11:29:08 AM] [Migrate  ] › ℹ  info      Current database version: none
nginx  | [7/1/2025] [11:29:08 AM] [Global   ] › ⬤  debug     CMD: [ -f '/etc/letsencrypt/credentials/credentials-50' ] || { mkdir -p /etc/letsencrypt/credentials 2> /dev/null; echo '# Cloudflare API token
nginx  | dns_cloudflare_api_token=****' > '/etc/letsencrypt/credentials/credentials-50' && chmod 600 '/etc/letsencrypt/credentials/credentials-50'; }
nginx  | [7/1/2025] [11:29:08 AM] [Global   ] › ⬤  debug     CMD: [ -f '/etc/letsencrypt/credentials/credentials-63' ] || { mkdir -p /etc/letsencrypt/credentials 2> /dev/null; echo '# Cloudflare API token
nginx  | dns_cloudflare_api_token=****' > '/etc/letsencrypt/credentials/credentials-63' && chmod 600 '/etc/letsencrypt/credentials/credentials-63'; }
nginx  | [7/1/2025] [11:29:08 AM] [Certbot  ] › ▶  start     Installing cloudflare...
nginx  | [7/1/2025] [11:29:08 AM] [Global   ] › ⬤  debug     CMD: . /opt/certbot/bin/activate && pip install --no-cache-dir cloudflare==4.0.* acme==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') certbot-dns-cloudflare==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+')  && deactivate
nginx  | [7/1/2025] [11:29:09 AM] [Certbot  ] › ✖  error     ERROR: Cannot install certbot-dns-cloudflare==4.0.0 and cloudflare==4.0.* because these package versions have conflicting dependencies.
nginx  | ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
nginx  |
nginx  | [7/1/2025] [11:29:09 AM] [Global   ] › ✖  error     Some plugins failed to install. Please check the logs above CommandError: Some plugins failed to install. Please check the logs above
nginx  |     at /app/lib/certbot.js:39:14
nginx  |     at Immediate.<anonymous> (/app/node_modules/batchflow/lib/batchflow.js:80:9)
nginx  |     at process.processImmediate (node:internal/timers:483:21) {
nginx  |   previous: undefined,
nginx  |   code: 1,
nginx  |   public: false
nginx  | }
```
Rolling back to 2.12.3 works fine.

**Nginx Proxy Manager Version**
2.12.4

**To Reproduce**
1. Update docker image from jc21/nginx-proxy-manager:2.12.3 to 2.12.4
2. Access the admin panel
3. Try to log in
4. Login fails

**Expected behavior**
Should be able to log in as usual after the upgrade

**Screenshots**
N/A

**Operating System**
Ubuntu 24.04.2 LTS
Docker version 26.1.3, build b72abbb

**Additional context**
- No issue with 2.12.3
- Similar issue: [#1769](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1769)
- No other errors are shown in docker logs
- `/api/tokens` returns a 502 error.(Thanks for @LukeSearle )

**Comment by LukeSearle** [comment]
I have the same problem. 

The browser console logs indicates getting `/api/tokens` returns a 502.

**Comment by paelan8a** [comment]
Oh, I forgot. Thanks!

**Comment by spirytuslove** [comment]
I'm also having login problems don't know how to fix it

**Comment by Robertwhitten87** [comment]
Same problem here.  Just rolled back to previous version and it's working fine. Logs look exactly the same as above with the added pip reporting conflicting dependencies.

**Comment by Joshndroid** [comment]
Same issue, just upgraded... cloudflare failing exactly the same

**Comment by drbadd** [comment]
I just ran into the same issue. Rolled back by adding the :2.12.3 tag to my unraid docker template and it's working again.

**Comment by santoshganti** [comment]
## Preliminary Investigation

The container is performing this installation via pip

```bash
. /opt/certbot/bin/activate && pip install --no-cache-dir cloudflare==4.0.* acme==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') certbot-dns-cloudflare==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+')  && deactivate
```

And the error is 

```text
ERROR: Cannot install certbot-dns-cloudflare==4.0.0 and cloudflare==4.0.* because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested cloudflare==4.0.*
    certbot-dns-cloudflare 4.0.0 depends on cloudflare<2.20 and >=2.19

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Changing the version in this command to `cloudflare==2.19.*` fixes the issues

```bash
. /opt/certbot/bin/activate && pip install --no-cache-dir cloudflare==2.19.* acme==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') certbot-dns-cloudflare==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+')  && deactivate
```

Likely Root cause is whatever script is generating the command for pip install & possibly  `certbot-dns-cloudflare` version 4 is accidentally applied to `cloudflare` package. 

---

#### MariaDB or Postgres

Rollbacks won't help in some cases because the migration lock happens, but doing the following might be unsafe

```sql
UPDATE `migrations_lock` SET
`index` = '1',
`is_locked` = '0'
WHERE `index` = '1';
```

I used an adminer container to connect to my NPM instance. 

Critically, issues persist with  both `mariadb` & `postgres` as well, `sqllite` folks maybe just need to fix the pip requirements.

**Comment by tom-kst** [comment]
I've returned to 2.12.3 at the moment. waiting for fixes

**Comment by jjjonesjr33** [comment]
Same issue here for me as well.

**Comment by AnSch1510** [comment]
Same here. Rollback seems to work with no problem

**Comment by jicho** [comment]
Same issue here with the login, I'm working with a sqllite db.

**Comment by hilee0602** [comment]
Same issue cannot login. /api/token error..

**Comment by Chacsam** [comment]
Same issue:
"Bad gateway" error on login and API unavailable

**Comment by MK-0x41** [comment]
Same issue here - backup restore to version 2.12.3 fixed it for now

**Comment by OPTips** [comment]
Same issue here. And with a high CPU usage also.

**Comment by MSommer95** [comment]
Same here, rollback to 2.12.3 worked fine for now.

**Comment by Selidie** [comment]
Can confirm the same for me.  Rolling back to 2.12.3 and all working.

**Comment by rsaffi** [comment]
Not only the `/api/tokens` endpoint throws the `502`, but I use `/api` to do healthchecks in Uptime Kuma and even that is throwing a `502`.

**Comment by iamggggs** [comment]
After upgrading from 2.12.3 to 2.12.4, I encountered the same issue. Rolling back to 2.12.3 worked fine. Please fix this, Tks.

**Comment by hummelmose** [comment]
I can confirm - Same issue here with 2.12.4 - Couldn't log in (API error) - Rolled back to 2.12.3, and everything again worked fine.

**Comment by neorolls** [comment]
Can confirm that a rollback to a previous version solves this error, in case anyone run into the same issue.

`
image: docker.io/jc21/nginx-proxy-manager:2.12.3
`

**Comment by Brainfish69** [comment]
Same issue. Rollback to 2.12.3 fixed it

**Comment by mabod** [comment]
Guys, is now every user with the same problem supposed to add a comment to this issue, like "I can confirm"? I hope not!

**Comment by ZoltrixGFC** [comment]
I can confirm

**Comment by SionS4R** [comment]
Temporary solved with:

docker exec -it <name_container> /bin/bash
source /opt/certbot/bin/activate

pip uninstall -y cloudflare certbot-dns-cloudflare
pip install certbot-dns-cloudflare==2.6.0 cloudflare==2.11.3

deactivate
exit

**Comment by oscarmadethis** [comment]
Same issues here with current `latest` version `2.12.4`. 
Accompanied with high cpu usage and huge quantities of dns queries to: 
```
pypi.org
files.pythonhosted.org
```
_Likely due to certbot-dns-cloudflare/cloudflare install script loop ..._

A rollback to a previous version solves this error, in case anyone run into the same issue.
```
image: docker.io/jc21/nginx-proxy-manager:2.12.3
```

**Comment by ShotokanZH** [comment]
The issue is in `/global/certbot-dns-plugins.json`

![Image](https://github.com/user-attachments/assets/47739d03-8e84-46f5-b0a9-d07c330d69dc)

Removing the cloudflare version and letting pip autoselect it from the dependency fixes it.

![Image](https://github.com/user-attachments/assets/1f1dee43-442b-4556-a58a-70f2eb3c698c)

Note:
Requires an app / container restart.

**Comment by byte21516** [comment]
Sadly [ShotokanZH](https://github.com/ShotokanZH) 's solution did not work for me :(
Using latest with sqlite. Also the location for me was /app/global/certbot-dns-plugins.json

**Comment by wouldntyouknow** [comment]
One more confirmation, rolling back a notch - all good again.

**Comment by byte21516** [comment]
Confirming, rolling back to 2.12.3 works :)

**Comment by w84no1** [comment]
> The issue is in `/global/certbot-dns-plugins.json`
> 
> ![Image](https://github.com/user-attachments/assets/47739d03-8e84-46f5-b0a9-d07c330d69dc)
> 
> Removing the cloudflare version and letting pip autoselect it from the dependency fixes it.
> 
> ![Image](https://github.com/user-attachments/assets/1f1dee43-442b-4556-a58a-70f2eb3c698c)
> 
> Note: Requires an app / container restart.

Thanks, this got me back in!

**Comment by dan1elhughes** [comment]
Proposed the above as a PR - https://github.com/NginxProxyManager/nginx-proxy-manager/pull/4614

**Comment by ther3zz** [comment]
> The issue is in `/global/certbot-dns-plugins.json`
> 
> ![Image](https://github.com/user-attachments/assets/47739d03-8e84-46f5-b0a9-d07c330d69dc)
> 
> Removing the cloudflare version and letting pip autoselect it from the dependency fixes it.
> 
> ![Image](https://github.com/user-attachments/assets/1f1dee43-442b-4556-a58a-70f2eb3c698c)
> 
> Note: Requires an app / container restart.

also confirming this fixed it

**Comment by ShotokanZH** [comment]
I'm glad my solution helped! Great job guys

**Comment by byte21516** [comment]
> I'm glad my solution helped! Great job guys

For me it did not, but great it helped so many others! Good job!

**Comment by marcosvfc** [comment]
I did what @ShotokanZH  said, and it worked for me.
Just execute this on the host (replace the "nginx" container name with your own container name):
`docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

**Comment by istbarp** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

Thanks a lot. Worked perfectly. Single line command. I like 💪

**Comment by kedu2o** [comment]
> I'm glad my solution helped! Great job guys

Ty, worked like a charm.

**Comment by nikolajhendel** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

This worked for me as well

**Comment by aheath70** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

This worked for me as well. Thanks for identifying the issue and for the workaround @ShotokanZH whilst we wait for the PR.

**Comment by laopaoer-wallet** [comment]
Same issue:
"Bad gateway" error on login and API unavailable

**Comment by chempner** [comment]
Same issue here

**Comment by byte21516** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

This worked for me too. When I did it by hand it did not. Thank you :)

**Comment by brianfromm** [comment]
**Same issue here.** Experienced similar symptoms where I was unable to log in, and some proxy hosts weren't loading correctly.

**Temporary workaround:**
- Pinned container to version `2.12.3` instead of `:latest`
- Modified Watchtower configuration to exclude NPM from automatic updates:
  ```yaml
  labels:
    - "com.centurylinklabs.watchtower.enable=false"
Current status: Stable on 2.12.3. Will monitor this issue before upgrading to newer versions.

**Comment by yinyuangu** [comment]
I have the same problem.

The browser console logs indicates getting /api/tokens returns a 502.

**Comment by tmakowka** [comment]
I encountered the same problem, CPU usage spiked on my server because of this. I reverted to 2.12.3 as a temporary workaround.

**Comment by yinyuangu** [comment]
Me too.
This is a significant bug that heavily impacts usage, and it's hard to accept.











> I encountered the same problem, CPU usage spiked on my server because of this. I reverted to 2.12.3 as a temporary workaround.

**Comment by byte21516** [comment]
> I encountered the same problem, CPU usage spiked on my server because of this. I reverted to 2.12.3 as a temporary workaround.

CPU also spiked on mine.
As soon as I did this the CPU spikes stopped and i was able to login to 2.12.4: 
`docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

**Comment by hummelmose** [comment]
> Me too. This is a significant bug that heavily impacts usage, and it's hard to accept.
> 
> > I encountered the same problem, CPU usage spiked on my server because of this. I reverted to 2.12.3 as a temporary workaround.

Hard to accept ? - It's an open source project - There are a solution further op in this thread. Thank the developer for maintaining a tool that we all use and love.

**Comment by malghana** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

Perfect Solution, container must be running to do this

**Comment by AlexanderCurl** [comment]
> > I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`
> 
> Perfect Solution, container must be running to do this

This also worked for me, took 2-3 container restarts after that, but works. Thanks! 👍🏻

**Comment by Skorsnet** [comment]
> > > I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`
> > 
> > 
> > Perfect Solution, container must be running to do this
> 
> This also worked for me, took 2-3 container restarts after that, but works. Thanks! 👍🏻

This worked for me as well and only took one restart of the container.  Thank you!

**Comment by JackDinn** [comment]
Same issue here on TrueNAS SCALE using the official app. After updating to v2.12.4, the container becomes unhealthy and never finishes starting. Rolling back to v2.12.3 fixes it immediately.

I saw the workaround about fixing the cloudflare plugin version in certbot-dns-plugins.json, but haven’t tried it yet.

Just checking — is it safe for me to stay on v2.12.3 and wait for the next update? Will this be fixed in 2.12.5?

Thanks!

**Comment by rick-pit** [comment]
Same issue, but workaround fix it!
Thanks

**Comment by JackDinn** [comment]
I decided to try and do the file adjustment "fix" . It does not work?

Like others, I encountered the known bug with cloudflare==4.0.* in the certbot-dns-plugins.json file. I applied the suggested fix:

I can see that I have correctly edited this file /app/global/certbot-dns-plugins.json
```
[root@docker-b1844808fadd:/app]# cat /app/global/certbot-dns-plugins.json | grep -i cloudflare
        "cloudflare": {
                "name": "Cloudflare",
                "package_name": "certbot-dns-cloudflare",
                "dependencies": "cloudflare acme=={{certbot-version}}",
                "credentials": "# Cloudflare API credentials used by Certbot\ndns_cloudflare_email = cloudflare@example.com\ndns_cloudflare_api_key = ",
                "full_plugin_name": "dns-cloudflare"
[root@docker-b1844808fadd:/app]# 
```
still an error even though we changed the file?

000957071s err="exchanging with 217.169.20.21:53 over udp: read udp 172.16.2.2:34884->217.169.20.21:53: i/o timeout"
2025-07-02 19:29:50.439807+00:002025/07/02 19:29:50.439598 ERROR response received addr=217.169.20.21:53 proto=udp status="exchanging with 217.169.20.21:53 over udp: read udp 172.16.2.2:47488->217.169.20.21:53: i/o timeout"
2025-07-02 19:29:50.439995+00:002025/07/02 19:29:50.439821 [error] dnsproxy: exchange failed upstream=217.169.20.21:53 question=";watchseries.bypassed.org.\tIN\t A" duration=20.001228629s err="exchanging with 217.169.20.21:53 over udp: read udp 172.16.2.2:47488->217.169.20.21:53: i/o timeout"

Then restarted the container (multiple times). The change was confirmed and persisted — but the container still fails to start properly. It's stuck in an unhealthy state, and logs continue showing:

[error] dnsproxy: exchange failed upstream=217.169.20.20:53 ... i/o timeout

I also tried overriding /etc/resolv.conf inside the container to use 1.1.1.1, but it made no difference.
What I’ve Tried So Far:

    Fixed certbot-dns-plugins.json line

    Restarted container several times

    Edited /etc/resolv.conf to bypass Docker DNS

    Verified the file change persisted

    DNS to most domains works from host, but NPM still fails on startup

It appears the container is trying to resolve a domain (e.g., watchseries.bypassed.org) that is timing out and causing the health check to fail.


EDIT :-

After many restarts i thought for a moment it was going to work but now iv got yet more errors. 

Now im getting Broken 30-ownership.sh in the logs.
```
/etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh: line 33: syntax error: unexpected end of file
s6-rc: warning: unable to start service prepare: command exited 2
```
I have not touched that file at all!

I do have this env var entire in truenas but thats been in there since i set it up. I cant remember what it does exactly but i know it would not run at all when i set it up without it.
```
S6_STAGE2_HOOK
sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
```


At this point, I’ve rolled back to v2.12.3, which works fine.
I shall wait for the update, this is all to much for me.

:(

**Comment by avatarmanz** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

Thanks this fixed my issue as well. You are a legend.

**Comment by ffalor** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

This worked. For the folks using unraid, if you don't want to use the exec command you can open the console and run the sed command there.

![Image](https://github.com/user-attachments/assets/d9013eaf-3ba6-4fc0-8864-4a5e303a1405)

`sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json`

and then restart the container

![Image](https://github.com/user-attachments/assets/ab3f7036-d663-4292-9a9c-5949a8423576)

**Comment by paulstelian97** [comment]
> I do have this env var entire in truenas but thats been in there since i set it up. I cant remember what it does exactly but i know it would not run at all when i set it up without it.
> 
> ```
> S6_STAGE2_HOOK
> sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> ```
> 
> At this point, I’ve rolled back to v2.12.3, which works fine. I shall wait for the update, this is all to much for me.
> 
> :(

@JackDinn  Try `sed -i 2,$d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh`. Note the "2," portion that I've added. Instead of making the file empty, this command only deletes starting from the second line to preserve the shebang. It clears _that_ error on my end, leaving me with only the one mentioned in the main issue here (the cloudflare plugin one)

P.S: I suspect the recent patch that broke everything was intended to make this change no longer necessary. And in my experience NPM _would_ start even without this, it would just take 6 hours.

**Comment by JackDinn** [comment]
Ok good morning all.

Back to this....

So i have applied both alterations but now im getting another error ^^

I show that both 30-ownership.sh & certbot-dns-plugins.json are correct
```
jack@TruenasScale ~ $ sudo docker ps | grep nginx
0330a0c30683   jc21/nginx-proxy-manager:2.12.4                                                        "/init"                  17 minutes ago   Up 2 minutes (unhealthy)   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:30020->81/tcp, :::30020->81/tcp                                                                                                                                               ix-nginx-proxy-manager-npm-1
jack@TruenasScale ~ $ sudo docker exec -it ix-nginx-proxy-manager-npm-1 cat /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
#!/command/with-contenv bash
jack@TruenasScale ~ $ sudo docker exec -it ix-nginx-proxy-manager-npm-1 sh -c "cat /app/global/certbot-dns-plugins.json | grep cloudflare"
        "cloudflare": {
                "package_name": "certbot-dns-cloudflare",
                "dependencies": "cloudflare acme=={{certbot-version}}",
                "credentials": "# Cloudflare API credentials used by Certbot\ndns_cloudflare_email = cloudflare@example.com\ndns_cloudflare_api_key = ",
                "full_plugin_name": "dns-cloudflare"
jack@TruenasScale ~ $ 
jack@TruenasScale ~ $ sudo docker restart ix-nginx-proxy-manager-npm-1
ix-nginx-proxy-manager-npm-1
jack@TruenasScale ~ $ 
```

but when i try to restart it i get


```
025-07-03 08:48:45.121653+00:00nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:4
2025-07-03 08:48:45.151842+00:00nginx: [emerg] open() "/run/nginx/nginx.pid" failed (13: Permission denied)
2025-07-03 08:48:46.159853+00:00[1;34m❯ [1;36mStarting nginx ...[0m
2025-07-03 08:48:46.165160+00:00nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:4
2025-07-03 08:48:46.195039+00:00nginx: [emerg] open() "/run/nginx/nginx.pid" failed (13: Permission denied)
2025-07-03 08:48:47.202547+00:00[1;34m❯ [1;36mStarting nginx ...[0m
2025-07-03 08:48:47.207705+00:00nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:4
2025-07-03 08:48:47.237627+00:00nginx: [emerg] open() "/run/nginx/nginx.pid" failed (13: Permission denied)
2025-07-03 08:48:48.244427+00:00[1;34m❯ [1;36mStarting nginx ...[0m
2025-07-03 08:48:48.249608+00:00nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:4
2025-07-03 08:48:48.279490+00:00nginx: [emerg] open() "/run/nginx/nginx.pid" failed (13: Permission denied)
2025-07-03 08:48:49.287787+00:00[1;34m❯ [1;36mStarting nginx ...[0m
2025-07-03 08:48:49.293142+00:00nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc
```

Now what is the problem :(


EDIT:

I changed the PID & UID to 0 in the truenas NPM setting. but now iv got yet another error to do with DNS?

What iv done so far:
    
    Modified 30-ownership.sh with sed -i '2,$d' to preserve the shebang.

    Updated certbot-dns-plugins.json to fix the cloudflare==4.0.* dependency issue.

    Changed the PID & UID both to zero.

DNS inside the container appears functional (getent hosts google.com resolves fine)

Docker is using 127.0.0.11, which maps to 1.1.1.1 as intended

However, the logs are still showing this repeatedly:

    exchange failed upstream=217.169.20.21:53 over udp: i/o timeout

I don’t know why it’s trying to use 217.169.20.20/21 — that’s not my system resolver anymore, and I can’t find any config in the container referencing those addresses.

Anyone know where this might be coming from or what else I can try?

**Comment by JackDinn** [comment]
Oh yea iv just figured that 217.169.20.21 & 217.169.20.20 are my ISP's provided DNS. They are set in Adguard's upstream. But why is it doing this and how do i fix it? 

The previous version of NPM is fine.

**Comment by goug76** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

I was also seeing this issue and this fixed it, am able to login now. Running on Ubuntu server with a PostgreSQL database.

**Comment by Arimanio** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

This worked perfectly. Thanks. Looks like the wildcard in the cloudflare version is causing the conflict. This removes the strict versioning requirement.

**Comment by gyrex** [comment]
> I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

This worked for me too. Thanks!

**Comment by TimGoll** [comment]
> Same issue here on TrueNAS SCALE using the official app. After updating to v2.12.4, the container becomes unhealthy and never finishes starting. Rolling back to v2.12.3 fixes it immediately.
> 
> I saw the workaround about fixing the cloudflare plugin version in certbot-dns-plugins.json, but haven’t tried it yet.
> 
> Just checking — is it safe for me to stay on v2.12.3 and wait for the next update? Will this be fixed in 2.12.5?
> 
> Thanks!

Can confirm that a rollback fixed the issue for me as well. I'll wait for the next release and see if this fixes it!

**Comment by fercoder23** [comment]
After I executed that "fix", I am now getting this error:
`docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

CommandError: Saving debug log to /tmp/letsencrypt-log/letsencrypt.log
Error determining zone_id: 6003 Invalid request headers. Please confirm that you have supplied valid Cloudflare API credentials. (Did you copy your entire API token/key? To use Cloudflare tokens, you'll need the python package cloudflare>=2.3.1. This certbot is running cloudflare 2.19.4)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details.

    at /app/lib/utils.js:16:13
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

Does anyone know how to fix this? 
Thanks

**Comment by JackDinn** [comment]
<img width="703" height="261" alt="Image" src="https://github.com/user-attachments/assets/871b27e1-d547-4bf2-b192-b10316a69f8b" />

The NPM version is still showing as 2.12.4 but Im sure that the Truenas version was 1.2.4, but now its showing 1.2.5 what exactly does that mean for this bug?

**Comment by aitor422** [comment]
> <img alt="Image" width="703" height="261" src="https://private-user-images.githubusercontent.com/5557560/462640612-871b27e1-d547-4bf2-b192-b10316a69f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE2NjUzNDgsIm5iZiI6MTc1MTY2NTA0OCwicGF0aCI6Ii81NTU3NTYwLzQ2MjY0MDYxMi04NzFiMjdlMS1kNTQ3LTRiZjItYjE5Mi1iMTAzMTZhNjlmOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MDRUMjEzNzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMzZjNjYThhNWIwZWIwYTRmODBiMTA1YmNiYWNiYTBmMWIwNWEyYTlmNDA3Y2NkODc0MDNiOWIyMzk0NmE3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rb98P6WCqaF3T2d4fchcwebUuTHCMlyjSm3Bsju9Psk">
> 
> The NPM version is still showing as 2.12.4 but Im sure that the Truenas version was 1.2.4, but now its showing 1.2.5 what exactly does that mean for this bug?

Truenas latest app update is unrelated to this bug, it is merely a description update (see [Truenas/apps #2699](https://github.com/truenas/apps/pull/2699))

**Comment by JackDinn** [comment]
Ah ok, i shall just wait for the main NPM update. Thx.

**Comment by ZeroDeth** [comment]
login problem too

**Comment by devo321** [comment]
Also having this issue
Running on unraid. Used this solution to fix:

> > I did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me. Just execute this on the host (replace the "nginx" container name with your own container name): `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`
> 
> This worked. For the folks using unraid, if you don't want to use the exec command you can open the console and run the sed command there.
> 
> ![Image](https://github.com/user-attachments/assets/d9013eaf-3ba6-4fc0-8864-4a5e303a1405)
> 
> `sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json`
> 
> and then restart the container
> 
> ![Image](https://github.com/user-attachments/assets/ab3f7036-d663-4292-9a9c-5949a8423576)

**Comment by MatzeKitt** [comment]
For me, v1.2.5 worked after changing the `sed` command to take ownership to `sed -i 2,$d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh`, as pointed out by @paulstelian97

**Comment by Acer854** [comment]
OK dumb question from a Linux/TrueNAS juvenile. How the heck do I open the .json file in shell? I see the screenshot about nano but nano is not a recognized command. Does one have to install nano into the docker image? If so, how?

**Comment by ShotokanZH** [comment]
> OK dumb question from a Linux/TrueNAS juvenile. How the heck do I open the .json file in shell? I see the screenshot about nano but nano is not a recognized command. Does one have to install nano into the docker image? If so, how?

As others pointed out, you can go directly with sed, but overall it's a debian based image, i just ran `apt update && apt install -y nano`

**Comment by Acer854** [comment]
> > OK dumb question from a Linux/TrueNAS juvenile. How the heck do I open the .json file in shell? I see the screenshot about nano but nano is not a recognized command. Does one have to install nano into the docker image? If so, how?
> 
> As others pointed out, you can go directly with sed, but overall it's a debian based image, i just ran `apt update && apt install -y nano`

I owe you a beer.

**Comment by JackDinn** [comment]
Yea you can use package managers in docker instances (depends on the container image). You can apt, apk, etc.), but if you want to try to install anything via a package manager in the base truenas Scale ssh then you can not, it all seems to be locked down. The OS is designed to be immutable in this respect, to ensure stability and upgradability.

Caught me out many times.

**Comment by JackDinn** [comment]
> For me, v1.2.5 worked after changing the `sed` command to take ownership to `sed -i 2,$d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh`, as pointed out by [@paulstelian97](https://github.com/paulstelian97)

1.2.5 is not working for me?  I updated the app to 1.2.5, then i edited the environment veritable. Then i restarted NPM.
I waited and waited.

After about 3 minutes i get a status of "unhealthy" in the SSH.
```
jack@TruenasScale ~ $ sudo docker ps | grep nginx
92b4689f6c20   jc21/nginx-proxy-manager:2.12.4                                                        "/init"                  3 minutes ago   Up 3 minutes (unhealthy)   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:30020->81/tcp, :::30020->81/tcp                                                                                                                                               ix-nginx-proxy-manager-npm-1
jack@TruenasScale ~ $ 
```

The GUI says its still deploying, but because the status in ssh says it was unhealthy i stopped it?

I tried with both following sed commands in the env vars

`sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh`
&
`sed -i 2,$d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh`

i even tried removing this env var all together but its still shows unhealthy after 3 minutes. 

Was i supposed to wait for longer even after the status changes to unhealthy? Some have said it takes 30 minutes?

**Comment by paulstelian97** [comment]
@JackDinn There's **TWO** issues that are combined together here, not just one. There's the one where the sed command needs to be changed to skip the very-long chown (6+ hours on my system), and then there's another one where the Cloudflare DNS plugin wouldn't download/install correctly due to a bug specific to this version. The expectation is that the second bug shall be fixed by an upcoming version, and the first one you'd use the second option.

Without the env var, if the container doesn't run as root, you would have issues because a very long duration chown runs EVERY TIME the container starts. Though I think they are working on making said chown last much less time, making this variable no longer necessary in the future.

**Comment by JackDinn** [comment]
I wish it would just work :(

**Comment by Acer854** [comment]
> Yea you can use package managers in docker instances (depends on the container image). You can apt, apk, etc.), but if you want to try to install anything via a package manager in the base truenas Scale ssh then you can not, it all seems to be locked down. The OS is designed to be immutable in this respect, to ensure stability and upgradability.
> 
> Caught me out many times.

I am able to install nano and edit the plugins json but then when I stop the app, restart it, and re-enter shell nano is gone and my json edits are gone. Is that normal or do I have a permissions issue or something?

**Comment by cammelspit** [comment]
I am using unraid and the "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" within the console from the unraid webui worked like a treat. 👍

**Comment by Loigzorn** [comment]
The release of [v2.12.5](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.12.5) resolved the issues for me.
I had previously updated to v2.12.4 and rolled back to v2.12.3.
With the version v2.12.5 running I can log in on the web UI, logs look normal as well and I have not encountered any errors so far. 
The cloudflare dependency that contributed to the behaviour is now correctly included, as far as I can tell:
[compare v2.12.4 and v2.12.5](https://github.com/NginxProxyManager/nginx-proxy-manager/compare/v2.12.4...v2.12.5) in the global/certbot-dns-plugins.json file


Can someone confirm on there setup?

**Comment by dmudgeau** [comment]
> The release of [v2.12.5](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.12.5) resolved the issues for me. I had previously updated to v2.12.4 and rolled back to v2.12.3. With the version v2.12.5 running I can log in on the web UI, logs look normal as well and I have not encountered any errors so far. The cloudflare dependency that contributed to the behaviour is now correctly included, as far as I can tell: [compare v2.12.4 and v2.12.5](https://github.com/NginxProxyManager/nginx-proxy-manager/compare/v2.12.4...v2.12.5) in the global/certbot-dns-plugins.json file
> 
> Can someone confirm on there setup?

I tried 2.12.15 and the issue persists. Only 2.12.13 worked for me so far

**Comment by byte21516** [comment]
> did what @ShotokanZH said, and it worked for me.
> Just execute this on the host (replace the "nginx" container name with your own container name):
> `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`

Used this fix in 2.12.4.
2.12.6 works without issues for me.

**Comment by coreyandrews** [comment]
> > did what [@ShotokanZH](https://github.com/ShotokanZH) said, and it worked for me.
> > Just execute this on the host (replace the "nginx" container name with your own container name):
> > `docker exec -it nginx sh -c "sed -i 's/cloudflare==4.0.\*/cloudflare/' /app/global/certbot-dns-plugins.json" && docker restart nginx`
> 
> Used this fix in 2.12.4. 2.12.6 works without issues for me.

Same here, only solution for me. I have locked my version till its fixed in a later version.

**Comment by TimGoll** [comment]
On TrueNAS I updated to 1.2.6 without any further changes and it worked for me

**Comment by Acer854** [comment]
> On TrueNAS I updated to 1.2.6 without any further changes and it worked for me

Same. The glitch has been fixed!

**Comment by Chacsam** [comment]
solved in v2.12.6 in a proxmox LXC

**Comment by moeinio** [comment]
It is still broken on TrueNAS 25.04.1

**Comment by Acer854** [comment]
v1.2.6/2.12.6 is working on my SCALE 25.04.1.

David Schatz
***@***.***

**Comment by W1BTR** [comment]
Still broken for me on 2.12.6 - sqlite database on debian docker. Changing to 2.12.3 also has this issue.

**Comment by paulstelian97** [comment]
Everyone on this issue be advised: the correct way to use newer versions of NPM is to remove the hook variable with sed that was used properly on older versions! Instead you want only one environment variable in TrueNAS (+ I guess other standard ones like timezone etc, TrueNAS makes them implicit): `SKIP_CERTBOT_OWNERSHIP=true`. That's it. No more `S6_*` variables. No more `*HOOK*` variables. Just one higher level variable directly.

**Comment by moeinio** [comment]
> SKIP_CERTBOT_OWNERSHIP=true

This fixed the issue for me, thanks.

**Comment by excalq** [comment]
For anyone on TrueNAS 24.04 (stuck on 2.12.4), the easy fix is adding `SKIP_CERTBOT_OWNERSHIP=true` as an environment variable in the TrueNAS "App" settings.
